---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golang
  namespace: playground
  labels:
    app: golang
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
